### ISSUE TITLE
Unreadable submission

### ISSUE THREAD

**Issue by dcjones** [UWSEDS/homework-4-documentation-and-style-lesnyder#1]
`test_dataframe.py` is a binary file, not a text file, and I'm unable to read it. Please resubmit with a text file, as well as pylint output.

0/7 points

**Comment by lesnyder** [comment]
new homework and pylint output submitted

**Comment by dcjones** [comment]
Documentation and and pylint score look good.

The code in the final test looks wrong (`test_creat_dataframe` is not a DataFrame method, and not otherwise defined), but I'm not grading on that. However -2 points late penalty, so 5/7 points.
